//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public decimal id { get; set; }
        public decimal Ins_id { get; set; }
        public string etablissement { get; set; }
        public string fonction { get; set; }
        public string periode { get; set; }
        public string description { get; set; }
        public Nullable<int> archived { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Inscrire Inscrire { get; set; }
    }
}
