//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FraisLocation
    {
        public decimal id { get; set; }
        public decimal Ins_id { get; set; }
        public decimal Ins_id2 { get; set; }
        public decimal Loc_id { get; set; }
        public string libelle { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<double> avance { get; set; }
        public Nullable<double> reste { get; set; }
        public string type { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<int> archived { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Location Location { get; set; }

        public Inscrire getPayeur()
        {
            NiovarJobEntities db = new NiovarJobEntities();
            if (!userId.HasValue) return null;
            Inscrire inscrire = db.Inscrire.Where(p => p.archived == 1 && p.id == Ins_id2).FirstOrDefault();
            return inscrire;
        }
    }
}
