//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.FraisLocation = new HashSet<FraisLocation>();
        }

        public decimal Ins_id { get; set; }
        public decimal Ins_id2 { get; set; }
        public decimal id { get; set; }
        public string periode { get; set; }
        public string heureTravail { get; set; }
        public string description { get; set; }
        public Nullable<decimal> montant { get; set; }
        public Nullable<int> signClient { get; set; }
        public Nullable<int> signCandidat { get; set; }
        public Nullable<decimal> remuneration { get; set; }
        public Nullable<System.DateTime> dateSgnClt { get; set; }
        public Nullable<System.DateTime> dateSgnCdt { get; set; }
        public Nullable<int> avisClient { get; set; }
        public Nullable<int> avisCandidat { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> archived { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<int> type { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FraisLocation> FraisLocation { get; set; }
        public virtual Inscrire Inscrire { get; set; }
    }
}
