//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Postuler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postuler()
        {
            this.Document = new HashSet<Document>();
            this.Paiement = new HashSet<Paiement>();
        }
        [NotMapped]
        public int nbreAccept { get; set; }

        [NotMapped]
        public int nbreApply { get; set; }

        [NotMapped]
        public String typeJob { get; set; }
        public decimal Ins_id { get; set; }
        public decimal Job_id { get; set; }
        public decimal id { get; set; }
        public string libelle { get; set; }
        public Nullable<System.DateTime> datePostule { get; set; }
        public string heurePostule { get; set; }
        public Nullable<double> remuneration { get; set; }
        public string etatAdmin { get; set; }
        public string etat { get; set; }
        public Nullable<int> archived { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string etatClient { get; set; }
        public string etatCandidat { get; set; }
        public string approbation { get; set; }
        public string signatures { get; set; }
        public string situationTravail { get; set; }
        public Nullable<System.DateTime> dateEmbauche { get; set; }
        public Nullable<System.DateTime> dateSignatures { get; set; }
        public Nullable<System.DateTime> dateEntrevue { get; set; }
        public string heure { get; set; }
        public string responsableEntrevue { get; set; }
        public string duree { get; set; }
        public string outils { get; set; }
        public Nullable<int> signatureClient { get; set; }
        public Nullable<System.DateTime> dateSignClient { get; set; }
        public Nullable<int> compagnyId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
        public virtual Inscrire Inscrire { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiement { get; set; }
    }
}
