//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Utilisateur
    {
        public decimal id { get; set; }
        public decimal Rol_id { get; set; }
        public string nom { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email est obligatoire")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> archived { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string allowNotification { get; set; }
        public string allowNewsletter { get; set; }

        public virtual Role Role { get; set; }
    }
}
